# Generated by Django 3.2.25 on 2025-11-28 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код')),
                ('description', models.CharField(max_length=500, verbose_name='Описание')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Категория')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Код оплаты',
                'verbose_name_plural': 'Коды оплат',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('month', models.IntegerField(verbose_name='Месяц')),
                ('half', models.IntegerField(choices=[(1, 'Первая половина месяца'), (2, 'Вторая половина месяца')], default=2, verbose_name='Половина месяца')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Период',
                'verbose_name_plural': 'Периоды',
                'ordering': ['-year', '-month', '-half'],
                'unique_together': {('year', 'month', 'half')},
            },
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/', verbose_name='Файл')),
                ('file_type', models.CharField(choices=[('codebook', 'Справочник кодов'), ('receipt', 'Квитанция')], max_length=20, verbose_name='Тип файла')),
                ('processed', models.BooleanField(default=False, verbose_name='Обработан')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payroll.payrollperiod', verbose_name='Период')),
            ],
            options={
                'verbose_name': 'Загруженный файл',
                'verbose_name_plural': 'Загруженные файлы',
            },
        ),
        migrations.CreateModel(
            name='PayrollEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_code', models.CharField(max_length=50, verbose_name='Исходный код')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payroll.paymentcode', verbose_name='Код оплаты')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='payroll.payrollperiod', verbose_name='Период')),
            ],
            options={
                'verbose_name': 'Запись ведомости',
                'verbose_name_plural': 'Записи ведомостей',
            },
        ),
    ]
