# Generated by Django 4.2.5 on 2023-10-06 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(max_length=30, null=True)),
                ('sn', models.CharField(max_length=30, null=True)),
                ('product', models.CharField(max_length=30, null=True)),
                ('cpu_model', models.CharField(max_length=50, null=True)),
                ('cpu_num', models.CharField(max_length=2, null=True)),
                ('cpu_vendor', models.CharField(max_length=30, null=True)),
                ('memory_part_number', models.CharField(max_length=30, null=True)),
                ('memory_manufacturer', models.CharField(max_length=30, null=True)),
                ('memory_size', models.CharField(max_length=20, null=True)),
                ('device_model', models.CharField(max_length=30, null=True)),
                ('device_version', models.CharField(max_length=30, null=True)),
                ('device_sn', models.CharField(max_length=30, null=True)),
                ('device_size', models.CharField(max_length=30, null=True)),
                ('osver', models.CharField(max_length=30, null=True)),
                ('hostname', models.CharField(max_length=30, null=True)),
                ('os_release', models.CharField(max_length=30, null=True)),
                ('ipaddr', models.GenericIPAddressField()),
            ],
        ),
        migrations.CreateModel(
            name='HostGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('members', models.ManyToManyField(to='hosting.host')),
            ],
        ),
    ]
