# Generated by Django 4.2.5 on 2023-10-10 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0002_host_hostgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='hosting.category'),
        ),
    ]
