# Generated by Django 3.2.24 on 2024-03-12 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0004_host_time_create_host_time_update_alter_host_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
