# Generated by Django 3.2.24 on 2024-03-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0005_host_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='checkbox_field',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='host',
            name='cpu_1_min',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='host',
            name='cpu_5_min',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='host',
            name='mem_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='host',
            name='mem_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='host',
            name='mem_util',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='host',
            name='uptime',
            field=models.BooleanField(default=False),
        ),
    ]
