# Generated by Django 3.2.24 on 2024-03-29 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0007_auto_20240321_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='NagiosHost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('host_id', models.CharField(max_length=100)),
            ],
        ),
    ]
