# Generated by Django 3.2.24 on 2024-04-08 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0008_nagioshost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NagiosHost',
        ),
        migrations.AddField(
            model_name='host',
            name='SNMP',
            field=models.BooleanField(default=False),
        ),
    ]
