# Generated by Django 3.2.24 on 2024-04-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0009_auto_20240408_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='nagios_flag',
            field=models.BooleanField(default=False),
        ),
    ]
