# Generated by Django 3.2.25 on 2024-05-14 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0010_host_nagios_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='data_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
