# Generated by Django 3.2.25 on 2024-05-14 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0011_host_data_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='data_created',
        ),
    ]
