# Generated by Django 3.2.25 on 2024-05-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0012_remove_host_data_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='hide_flag',
            field=models.BooleanField(default=False),
        ),
    ]
