# Generated by Django 3.2.25 on 2024-05-31 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0013_host_hide_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='parents',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
