# Generated by Django 3.2.25 on 2024-06-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0014_host_parents'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='device_type',
            field=models.CharField(choices=[('server', 'Server'), ('switch', 'Switch'), ('printer', 'Printer')], default=False, max_length=50),
        ),
    ]
