# Generated by Django 3.2.25 on 2024-06-14 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0016_alter_host_device_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='device_type',
            field=models.CharField(choices=[('server', 'Server'), ('switch', 'Switch'), ('printer', 'Printer')], default=False, max_length=50),
        ),
    ]
