# Generated by Django 3.2.25 on 2024-06-14 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0017_alter_host_device_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='device_type',
            field=models.CharField(choices=[('servers', 'Сервер'), ('switches', 'Коммутатор'), ('printers', 'Принтер')], default=False, max_length=50),
        ),
    ]
