# Generated by Django 3.2.25 on 2024-06-14 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0018_alter_host_device_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='device_type',
            field=models.CharField(blank=True, choices=[('servers', 'Server'), ('switches', 'Switch'), ('printers', 'Printer')], default=False, max_length=50, null=True),
        ),
    ]
