# Generated by Django 3.2.25 on 2024-08-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0019_alter_host_device_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='com_str',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
