# Generated by Django 3.2.25 on 2024-12-03 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0020_host_com_str'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='parents',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='hosting.host'),
        ),
    ]
