# Generated by Django 3.2.25 on 2024-12-18 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0022_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='device_type',
            field=models.CharField(blank=True, choices=[('server', 'Сервер'), ('switche', 'Коммутатор'), ('printer', 'Принтер')], default=False, max_length=50, null=True),
        ),
    ]
