# Generated by Django 3.2.25 on 2024-12-18 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0023_alter_host_device_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='device_type',
            field=models.CharField(blank=True, choices=[('server', 'Server'), ('switche', 'Switch'), ('printer', 'Printer'), ('ups', 'UPS')], default=False, max_length=50, null=True),
        ),
    ]
