# Generated by Django 3.2.25 on 2024-12-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0027_alter_host_device_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='device_type',
            field=models.CharField(blank=True, choices=[('servers', 'Сервер'), ('switches', 'Коммутатор'), ('network-printers', 'Принтер'), ('UPS', 'ИБП')], default=False, max_length=50, null=True),
        ),
    ]
