# Generated by Django 3.2.25 on 2024-12-19 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0028_alter_host_device_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='status_information',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
