# Generated by Django 3.2.25 on 2024-12-19 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0029_service_status_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='bat_temp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='host',
            name='bat_time_work',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='host',
            name='bat_vol',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='host',
            name='run_reman',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='host',
            name='stat_charge',
            field=models.BooleanField(default=False),
        ),
    ]
