# Generated by Django 3.2.25 on 2025-01-20 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0030_auto_20241219_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
