# Generated by Django 3.2.25 on 2025-02-12 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0031_host_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ifdescr', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('last_checked', models.DateTimeField(auto_now=True)),
                ('ifinoct', models.CharField(blank=True, max_length=255, null=True)),
                ('ifoutoct', models.CharField(blank=True, max_length=255, null=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='hosting.host')),
            ],
            options={
                'unique_together': {('host', 'ifdescr')},
            },
        ),
    ]
