# Generated by Django 3.2.25 on 2025-02-13 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0032_ports'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='host',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
