# Generated by Django 3.2.25 on 2025-03-06 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0033_auto_20250213_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_id', models.CharField(max_length=255, unique=True)),
                ('color', models.CharField(max_length=7)),
                ('weight', models.IntegerField()),
            ],
        ),
    ]
