# Generated by Django 3.2.25 on 2025-03-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0034_linesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='linesettings',
            name='line_type',
            field=models.CharField(choices=[('solid', 'Solid'), ('dashed', 'Dashed'), ('dotted', 'Dotted'), ('dash-dot', 'Dash-dot')], default='solid', max_length=10),
        ),
    ]
