# Generated by Django 3.2.25 on 2025-03-11 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0035_linesettings_line_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waypoints', models.JSONField(default=list)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_routes', to='hosting.host')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_routes', to='hosting.host')),
            ],
        ),
    ]
