# Generated by Django 3.2.25 on 2025-11-26 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0037_nodeposition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='device_type',
            field=models.CharField(blank=True, choices=[('servers', 'Server'), ('switches', 'Switch'), ('routers', 'Router'), ('computers', 'Computer'), ('network-printers', 'Printer'), ('UPS', 'UPS')], default=False, max_length=50, null=True),
        ),
    ]
