# Generated by Django 3.2.25 on 2025-12-01 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0038_alter_host_device_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='hostname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
