# Generated by Django 5.2.17 on 2026-08-12 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0039_alter_host_hostname'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#7a5cff', max_length=7)),
                ('default_action', models.CharField(choices=[('allow', 'Allow'), ('deny', 'Deny')], default='deny', max_length=5)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='host',
            name='segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosts', to='hosting.networksegment'),
        ),
        migrations.CreateModel(
            name='SegmentPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('action', models.CharField(choices=[('allow', 'Allow'), ('deny', 'Deny')], max_length=5)),
                ('protocol', models.CharField(choices=[('any', 'Any'), ('tcp', 'TCP'), ('udp', 'UDP'), ('icmp', 'ICMP')], default='any', max_length=4)),
                ('port', models.PositiveIntegerField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_policies', to='hosting.networksegment')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_policies', to='hosting.networksegment')),
            ],
            options={
                'verbose_name_plural': 'segment policies',
                'ordering': ('priority', 'pk'),
                'constraints': [models.CheckConstraint(condition=models.Q(('port__isnull', True), models.Q(('port__gte', 1), ('port__lte', 65535)), _connector='OR'), name='hosting_segment_policy_valid_port')],
            },
        ),
    ]
