# Generated by Django 5.2.17 on 2026-08-13 06:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosting', '0040_networksegment_host_segment_segmentpolicy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networksegment',
            name='color',
            field=models.CharField(default='#7a5cff', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Enter a valid HEX color.')]),
        ),
        migrations.AddConstraint(
            model_name='segmentpolicy',
            constraint=models.CheckConstraint(condition=models.Q(('protocol__in', ('tcp', 'udp')), ('port__isnull', True), _connector='OR'), name='hosting_segment_policy_port_protocol'),
        ),
        migrations.AddConstraint(
            model_name='segmentpolicy',
            constraint=models.UniqueConstraint(fields=('source', 'destination', 'priority'), name='hosting_segment_policy_unique_priority'),
        ),
    ]
