# Generated by Django 3.2.25 on 2025-11-28 09:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeDictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='payslip_analyzer/dictionaries/', verbose_name='Файл справочника')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Оригинальное имя файла')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('processed', models.BooleanField(default=False, verbose_name='Обработан')),
                ('codes_found', models.IntegerField(default=0, verbose_name='Найдено кодов')),
                ('codes_added', models.IntegerField(default=0, verbose_name='Добавлено кодов')),
                ('error_message', models.TextField(blank=True, verbose_name='Ошибка обработки')),
            ],
            options={
                'verbose_name': 'Загруженный справочник',
                'verbose_name_plural': 'Загруженные справочники',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=10, unique=True, verbose_name='Код')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('code_type', models.CharField(choices=[('income', 'Начисление'), ('deduction', 'Удержание')], default='income', max_length=10, verbose_name='Тип')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Код оплаты',
                'verbose_name_plural': 'Коды оплат',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='PaySlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(db_index=True, verbose_name='Период (месяц)')),
                ('half', models.IntegerField(choices=[(1, 'Первая половина (1-15)'), (2, 'Вторая половина (16-31)')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)], verbose_name='Половина месяца')),
                ('total_income', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Итого начислено')),
                ('total_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Итого удержано')),
                ('net_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='К выплате')),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='payslip_analyzer/receipts/%Y/%m/', verbose_name='Изображение квитанции')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Платежная ведомость',
                'verbose_name_plural': 'Платежные ведомости',
                'ordering': ['-period', '-half'],
            },
        ),
        migrations.CreateModel(
            name='PaySlipItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('income', 'Начисление'), ('deduction', 'Удержание')], db_index=True, max_length=10, verbose_name='Тип')),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Месяц')),
                ('code', models.CharField(db_index=True, max_length=10, verbose_name='Код')),
                ('rv', models.DecimalField(blank=True, decimal_places=2, help_text='Рабочее время: часы или дни', max_digits=10, null=True, verbose_name='РВ (часы/дни)')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('code_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payslip_items', to='payslip_analyzer.paymentcode', verbose_name='Справочник кода')),
                ('payslip_analyzer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payslip_analyzer.payslip_analyzer', verbose_name='Ведомость')),
            ],
            options={
                'verbose_name': 'Строка ведомости',
                'verbose_name_plural': 'Строки ведомости',
                'ordering': ['item_type', 'month', 'code'],
            },
        ),
        migrations.AddIndex(
            model_name='payslip_analyzer',
            index=models.Index(fields=['period', 'half'], name='payslip_ana_period_5888e7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='payslip_analyzer',
            unique_together={('period', 'half')},
        ),
    ]
